# Generated by Django 5.2.6 on 2025-09-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
