# Generated by Django 5.2.6 on 2025-09-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_alter_propiedad_precio_alter_propiedad_titulo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propiedad',
            table='propiedad',
        ),
    ]
