# Generated by Django 5.2.8 on 2025-11-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_alter_propiedad_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propiedad',
            table='propiedades_propiedad',
        ),
    ]
