# Generated by Django 5.2.8 on 2025-11-28 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_alter_propiedad_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=10)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
            ],
            options={
                'db_table': 'propiedades_usuario',
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_negocio',
            field=models.CharField(choices=[('COMP', 'Comprar'), ('ARR', 'Arrendar')], default='ARR', max_length=4),
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_propiedad', models.ImageField(upload_to='propiedades/')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad')),
            ],
            options={
                'db_table': 'imagen_propiedad',
            },
        ),
        migrations.CreateModel(
            name='FotoDePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(upload_to='usuarios/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.usuario')),
            ],
        ),
    ]
